[[0, 0, 0], 12, {"submitted": 1542056272.2667, "finished": 1542056442.935136, "started": 1542056272.266773}, null, "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/Users/Jose/Documents/Homeworks/M.Sc. Informatik/I/Lab Robotics and Reinforcement Learning/Ubungen/U02/random_search.py\", line 138, in compute\n    new_weights = [glorot_uniform()(w.shape).eval() for w in initial_weights]\n  File \"/Users/Jose/Documents/Homeworks/M.Sc. Informatik/I/Lab Robotics and Reinforcement Learning/Ubungen/U02/random_search.py\", line 138, in <listcomp>\n    new_weights = [glorot_uniform()(w.shape).eval() for w in initial_weights]\n  File \"/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/framework/ops.py\", line 713, in eval\n    return _eval_using_default_session(self, feed_dict, self.graph, session)\n  File \"/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/framework/ops.py\", line 5143, in _eval_using_default_session\n    raise ValueError(\"Cannot evaluate tensor using `eval()`: No default \"\nValueError: Cannot evaluate tensor using `eval()`: No default session is registered. Use `with sess.as_default()` or pass an explicit session to `eval(session=sess)`\n"]
